# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graffio < Formula
  desc "Internet Graffiti Wall"
  homepage "https://github.com/shubhxms/graffio"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shubhxms/graffio/releases/download/v0.1.7/graffio_Darwin_arm64.tar.gz"
      sha256 "df05cd40c41e4b459aa740e11ba0f8ec837014c2d9fb853e022d43e9d8e755c1"

      def install
        bin.install "graffio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shubhxms/graffio/releases/download/v0.1.7/graffio_Darwin_x86_64.tar.gz"
      sha256 "533ba711974a897dcaf3840929b9422bdc95c1628396b62fad9778fa918ccfba"

      def install
        bin.install "graffio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubhxms/graffio/releases/download/v0.1.7/graffio_Linux_arm64.tar.gz"
      sha256 "9a77ac5a8cdcc1de307fda7c55860737ef0f11b10a9717aa3c0b86558670e8ff"

      def install
        bin.install "graffio"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shubhxms/graffio/releases/download/v0.1.7/graffio_Linux_x86_64.tar.gz"
      sha256 "63c2250931c14ac00d29ace8b0e6d52dc710d5b72c66d521cd2dcba6c173485f"

      def install
        bin.install "graffio"
      end
    end
  end
end
