# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SharedBlog < Formula
  desc "Internet Graffiti Wall"
  homepage "https://github.com/shubhxms/shared-blog"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shubhxms/shared-blog/releases/download/v0.1.4/shared-blog_Darwin_arm64.tar.gz"
      sha256 "43fdd93b035d9cfc3db7e797bccfd42e63ddea14b8e51499b95cd2f5454a1ae2"

      def install
        bin.install "shared-blog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shubhxms/shared-blog/releases/download/v0.1.4/shared-blog_Darwin_x86_64.tar.gz"
      sha256 "33da779e3ff43b5c70abd293b18065b9af9d81c13d66e4a9178d69e3449bb93e"

      def install
        bin.install "shared-blog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shubhxms/shared-blog/releases/download/v0.1.4/shared-blog_Linux_arm64.tar.gz"
      sha256 "b5a656889b7b3bfe09f980fbc577f2292ac7de773bfe23b9ba83b88c33779b1b"

      def install
        bin.install "shared-blog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shubhxms/shared-blog/releases/download/v0.1.4/shared-blog_Linux_x86_64.tar.gz"
      sha256 "c7f1e6e1012e7ed5f53e582f1b8bd0dddadb70a5ceab9056afd3eab089daebaa"

      def install
        bin.install "shared-blog"
      end
    end
  end
end
